name: Convert TXT to SRS for sing-box1.8~1.9

on:
  workflow_dispatch:
  schedule:
    - cron: '5 */8 * * *'  # Run every 8 hours

jobs:
  install-and-compile:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Install Sing-Box
    - name: Install Sing-Box
      run: |
        bash <(curl -fsSL https://sing-box.app/deb-install.sh)

    # Step 3: Download JSON file
    - name: Download JSON file
      run: |
        curl -o megamori.json https://raw.githubusercontent.com/hyfink/megamori/main/megamori.json

    # Step 4: Convert AdGuard DNS Filter to SRS format
    - name: Convert AdGuard DNS Filter to megamori.srs
      run: |
        sing-box rule-set compile --output megamori.srs megamori.json

    # Step 5: Check for changes and commit if necessary
    - name: Commit and Push SRS file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add megamori.srs
        git commit -m "Auto-update megamori.srs" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
